<?
$PERM["services"]["8"]="X";
$PERM["services"]["5"]="W";
$PERM["products"]["8"]="X";
$PERM["products"]["5"]="W";
$PERM["obyavleniya"]["8"]="X";
$PERM["o-servise"]["8"]="X";
$PERM["contacts"]["8"]="X";
$PERM["contacts"]["5"]="W";
$PERM["company"]["8"]="X";
$PERM["company"]["5"]="W";
$PERM["bitrix"]["2"]="D";
$PERM["bitrix"]["3"]="D";
$PERM["bitrix"]["4"]="D";
$PERM["bitrix"]["8"]="D";
$PERM["bitrix"]["6"]="D";
$PERM["bitrix"]["7"]="D";
$PERM["bitrix"]["5"]="D";
$PERM["bitrix"]["*"]="R";
$PERM["lichnyy-kabinet-pokupatelya"]["*"]="D";
$PERM["lichnyy-kabinet-pokupatelya"]["6"]="X";
$PERM["lichnyy-kabinet-prodavtsa"]["*"]="D";
$PERM["lichnyy-kabinet-prodavtsa"]["G7"]="X";
$PERM["search"]["5"]="W";
$PERM["index.php"]["5"]="W";
$PERM["/"]["*"]="R";
?>